"""Add stock game models

Revision ID: 387a928ad536
Revises: eecbe71e35ea
Create Date: 2025-06-06 17:56:44.921052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387a928ad536'
down_revision = 'eecbe71e35ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('buy_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['game_portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['game_portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_transaction')
    op.drop_table('game_position')
    op.drop_table('game_portfolio')
    # ### end Alembic commands ###
