"""empty message

Revision ID: f94a2140d427
Revises: 004eaac264dd
Create Date: 2025-06-05 19:13:29.502093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94a2140d427'
down_revision = '004eaac264dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('ticker')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('ticker')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticker', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
